### PR TITLE
add mood tracker files

### PR DESCRIPTION
**Pull request by IlaganJireh**
Good day, I have made files for our mood tracker page, kindly review, thank you!

### CODE REVIEW

**Review by Gasta-Marc-Oliver — CHANGES_REQUESTED** [review]
Hello Andrei, please utilize and integrate a connection of our mood tracker to our database. Thank you

**Comment by Trinidad-KianLee** [comment]
Hi, jireh!

 I would like to suggest to add div line spaces for better code readability. Also in your css, there lines of code in there that doesn't have a proper spacing. Thank you!

**Review by Trinidad-KianLee — APPROVED** [review]
looks good to me

**Review by Trinidad-KianLee — APPROVED** [review]
Good day, Jireh.

It looks good to me now

**Review by Gasta-Marc-Oliver — APPROVED** [review]

**Comment by Gasta-Marc-Oliver** [comment]
Hello Andrei, I have seen the changes you made and it looks good to me now. Thank you.

**Pull request merged**
