### PR TITLE
Add update changes to home-page.php and home-page.css

### PR DESCRIPTION
**Pull request by armedillaalliyah**
Hi team! I made changes to our home-page.php and home-page.css, please review my codes. Thank you!

### CODE REVIEW

**Review by IlaganJireh — APPROVED** [review]
Good day Alliyah, it seems all of the changes you did looks good to me, will approve this now, thank you for your patience!

**Comment by Trinidad-KianLee** [comment]
Hello, Alliyah.

As you can see there is a merge conflict, you should pull the changes first in the main and double check yung linking. All the styles should be put in the styles folder. Thank you!

**Review by IlaganJireh — CHANGES_REQUESTED** [review]
Hello, i see that there are some files that you need to pull first and fix the merge conflicts that has occured, thanks.

**Comment by armedillaalliyah** [comment]
hi team! i did some changes, please review my code!

**Review by Trinidad-KianLee — CHANGES_REQUESTED** [review]
add spaces in the divs for better readability

**Review by Trinidad-KianLee — APPROVED** [review]

**Review by IlaganJireh — APPROVED** [review]

**Pull request merged**
