### PR TITLE
add updates, update proper file name

### PR DESCRIPTION
**Pull request by Trinidad-KianLee**
Good day, Team!

In here, I fixed our main_page and add functionality to it as well as enhacing the design. I also rename our files into proper format. Kindly review my code. Thank you!

### CODE REVIEW

**Review by Escuro-JohnDenielL — CHANGES_REQUESTED** [review]
Everything looks good!, I would like to suggest to add div line spaces as well

**Comment by Trinidad-KianLee** [comment]
Got it! I will add some spaces now.

**Review by Escuro-JohnDenielL — APPROVED** [review]
Looks good bro!

**Comment by Trinidad-KianLee** [comment]
I also update my js to that it follows the coding guidelines. Kindly review it, too. Thank you!

**Pull request merged**
